# Generated by Django 4.0.4 on 2022-05-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Дата посещения')),
                ('longitude', models.CharField(max_length=255, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=255, verbose_name='Широта')),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tradepoint')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.worker')),
            ],
        ),
        migrations.AddField(
            model_name='tradepoint',
            name='workers',
            field=models.ManyToManyField(to='shop.worker'),
        ),
    ]
